/*
  # Add product titles

  1. Changes
    - Add title column to products table
    - Update all products with their titles
    - Make title column required
*/

-- Add title column
ALTER TABLE products ADD COLUMN title text;

-- Update existing products with titles
UPDATE products SET title = 
  CASE id
    WHEN 'tamiya-dyna-storm-blaster-tr15t-blue-bulkhead' THEN 'Tamiya Dyna Storm Blaster TR15T Blue Bulkhead'
    WHEN 'tamiya-trf201-211-201xmw-silver-anodized-hinge-pin-brace' THEN 'Tamiya TRF201/211/201XMW Silver Anodized Hinge Pin Brace'
    WHEN 'tamiya-trf201-211-201xmw-blue-anodized-hinge-pin-brace' THEN 'Tamiya TRF201/211/201XMW Blue Anodized Hinge Pin Brace'
    WHEN 'tamiya-trf201-211-201xmw-black-anodized-hinge-pin-brace' THEN 'Tamiya TRF201/211/201XMW Black Anodized Hinge Pin Brace'
    WHEN 'tamiya-xv01-td4-spur-gear-flange-pressure-plate' THEN 'Tamiya XV01/TD4 Spur Gear Flange Pressure Plate'
    WHEN 'tamiya-ta01-ta02-df01-top-force-gearbox-shaft-set' THEN 'Tamiya TA01/TA02/DF01 Top Force Gearbox Shaft Set'
    WHEN 'yokomo-super-dogfighter-rere-yz870c-bulkheads' THEN 'Yokomo Super Dogfighter ReRe YZ870C Bulkheads'
    WHEN 'tamiya-df03-dark-impact-blue-heat-sink' THEN 'Tamiya DF03 Dark Impact Blue Heat Sink'
    WHEN 'tamiya-df03-dark-impact-black-heat-sink' THEN 'Tamiya DF03 Dark Impact Black Heat Sink'
    WHEN 'tamiya-df03-dark-impact-silver-heat-sink' THEN 'Tamiya DF03 Dark Impact Silver Heat Sink'
    WHEN 'tamiya-df03-dark-impact-red-heat-sink' THEN 'Tamiya DF03 Dark Impact Red Heat Sink'
    WHEN 'tamiya-dyna-storm-blaster-tr15t-black-e5-motor-guard' THEN 'Tamiya Dyna Storm Blaster TR15T Black E5 Motor Guard'
    WHEN 'tamiya-dyna-storm-blaster-tr15t-red-e5-motor-guard' THEN 'Tamiya Dyna Storm Blaster TR15T Red E5 Motor Guard'
    WHEN 'tamiya-top-force-df01-blue-servo-posts' THEN 'Tamiya Top Force DF01 Blue Servo Posts'
    WHEN 'tamiya-trf201-211-201xmw-black-rear-arm-mount' THEN 'Tamiya TRF201/211/201XMW Black Rear Arm Mount'
    WHEN 'tamiya-trf201-211-201xmw-blue-rear-arm-mount' THEN 'Tamiya TRF201/211/201XMW Blue Rear Arm Mount'
    WHEN 'tamiya-trf201-211-201xmw-silver-rear-arm-mount' THEN 'Tamiya TRF201/211/201XMW Silver Rear Arm Mount'
    WHEN 'tamiya-trf201-211-201xmw-red-rear-arm-mount' THEN 'Tamiya TRF201/211/201XMW Red Rear Arm Mount'
    WHEN 'tamiya-dyna-storm-blaster-tr15t-black-d7-chassis-brace' THEN 'Tamiya Dyna Storm Blaster TR15T Black D7 Chassis Brace'
    WHEN 'tamiya-dyna-storm-blaster-tr15t-silver-d7-chassis-brace' THEN 'Tamiya Dyna Storm Blaster TR15T Silver D7 Chassis Brace'
    WHEN 'tamiya-dyna-storm-blaster-tr15t-red-d7-chassis-brace' THEN 'Tamiya Dyna Storm Blaster TR15T Red D7 Chassis Brace'
    WHEN 'tamiya-dyna-storm-blaster-tr15t-blue-d7-chassis-brace' THEN 'Tamiya Dyna Storm Blaster TR15T Blue D7 Chassis Brace'
    WHEN 'tamiya-dyna-storm-blaster-tr15t-blue-anodized-parts' THEN 'Tamiya Dyna Storm Blaster TR15T Blue Anodized Parts Set'
    WHEN 'tamiya-dyna-storm-top-force-df01-egress-avante-wing-mount' THEN 'Tamiya Dyna Storm/Top Force/DF01/Egress/Avante Wing Mount'
    WHEN 'tamiya-top-force-df01-silver-servo-posts' THEN 'Tamiya Top Force DF01 Silver Servo Posts'
    WHEN 'tamiya-ta01-ta02-df01-front-gearbox-reinforcement' THEN 'Tamiya TA01/TA02/DF01 Front Gearbox Reinforcement'
    WHEN 'tamiya-dyna-storm-blaster-tr15t-black-d4-gearbox-link' THEN 'Tamiya Dyna Storm Blaster TR15T Black D4 Gearbox Link'
    WHEN 'tamiya-dyna-storm-blaster-tr15t-red-d4-gearbox-link' THEN 'Tamiya Dyna Storm Blaster TR15T Red D4 Gearbox Link'
    WHEN 'tamiya-dyna-storm-blaster-tr15t-blue-d4-gearbox-link' THEN 'Tamiya Dyna Storm Blaster TR15T Blue D4 Gearbox Link'
    WHEN 'tamiya-manta-ray-df01-black-wing-holder' THEN 'Tamiya Manta Ray DF01 Black Wing Holder'
    WHEN 'tamiya-manta-ray-df01-blue-wing-holder' THEN 'Tamiya Manta Ray DF01 Blue Wing Holder'
    WHEN 'tamiya-manta-ray-df01-wing-holder' THEN 'Tamiya Manta Ray DF01 Wing Holder'
    WHEN 'yokomo-super-dogfighter-rere-yz870c-motor-mount' THEN 'Yokomo Super Dogfighter ReRe YZ870C Motor Mount'
    WHEN 'tamiya-top-force-df01-anodized-hinge-pin-brace' THEN 'Tamiya Top Force DF01 Anodized Hinge Pin Brace'
    WHEN 'tamiya-top-force-df01-silver-anodized-upgrade-kit' THEN 'Tamiya Top Force DF01 Silver Anodized Upgrade Kit'
    WHEN 'tamiya-top-force-df01-silver-j7' THEN 'Tamiya Top Force DF01 Silver J7'
    WHEN 'tamiya-gearbox-reinforcement-black' THEN 'Tamiya Gearbox Reinforcement Black'
    WHEN 'tamiya-gearbox-reinforcement-red' THEN 'Tamiya Gearbox Reinforcement Red'
    WHEN 'tamiya-gearbox-reinforcement-blue' THEN 'Tamiya Gearbox Reinforcement Blue'
    WHEN 'tamiya-gearbox-reinforcement-silver' THEN 'Tamiya Gearbox Reinforcement Silver'
    WHEN 'tamiya-top-force-df01-blue-hinge-pin-brace' THEN 'Tamiya Top Force DF01 Blue Hinge Pin Brace'
    WHEN 'tamiya-top-force-df01-anodized-steering-brace' THEN 'Tamiya Top Force DF01 Anodized Steering Brace'
    WHEN 'tamiya-gearbox-motor-mount-black' THEN 'Tamiya Gearbox Motor Mount Black'
    WHEN 'tamiya-gearbox-motor-mount-red' THEN 'Tamiya Gearbox Motor Mount Red'
    WHEN 'tamiya-gearbox-motor-mount-silver' THEN 'Tamiya Gearbox Motor Mount Silver'
    WHEN 'tamiya-gearbox-motor-mount-blue' THEN 'Tamiya Gearbox Motor Mount Blue'
    WHEN 'tamiya-top-force-df01-blue-steering-brace' THEN 'Tamiya Top Force DF01 Blue Steering Brace'
    WHEN 'tamiya-dyna-storm-blaster-tr15t-black-bulkhead' THEN 'Tamiya Dyna Storm Blaster TR15T Black Bulkhead'
    WHEN 'tamiya-top-force-df01-anodized-upgrade-kit' THEN 'Tamiya Top Force DF01 Anodized Upgrade Kit'
    WHEN 'tamiya-top-force-df01-anodized-j7' THEN 'Tamiya Top Force DF01 Anodized J7'
    WHEN 'tamiya-top-force-df01-wing-holder' THEN 'Tamiya Top Force DF01 Wing Holder'
    WHEN 'tamiya-top-force-df01-wing-holder-blue' THEN 'Tamiya Top Force DF01 Wing Holder Blue'
    WHEN 'tamiya-top-force-df01-wing-holder-red' THEN 'Tamiya Top Force DF01 Wing Holder Red'
    WHEN 'tamiya-top-force-df01-wing-holder-silver' THEN 'Tamiya Top Force DF01 Wing Holder Silver'
    WHEN 'tamiya-top-force-df01-black-servo-posts' THEN 'Tamiya Top Force DF01 Black Servo Posts'
    WHEN 'tamiya-top-force-df01-silver-gearbox-cover' THEN 'Tamiya Top Force DF01 Silver Gearbox Cover'
    WHEN 'tamiya-top-force-df01-black-hinge-pin-brace' THEN 'Tamiya Top Force DF01 Black Hinge Pin Brace'
    WHEN 'tamiya-top-force-df01-blue-j7' THEN 'Tamiya Top Force DF01 Blue J7'
    WHEN 'tamiya-top-force-df01-anodized-gearbox-cover' THEN 'Tamiya Top Force DF01 Anodized Gearbox Cover'
    WHEN 'tamiya-top-force-df01-sc3-damper-mount' THEN 'Tamiya Top Force DF01 SC3 Damper Mount'
    WHEN 'tamiya-top-force-df01-silver-j3' THEN 'Tamiya Top Force DF01 Silver J3'
    WHEN 'tamiya-gearbox-reinforcement-set-red' THEN 'Tamiya Gearbox Reinforcement Set Red'
    WHEN 'tamiya-top-force-df01-anodized-j3' THEN 'Tamiya Top Force DF01 Anodized J3'
    WHEN 'tamiya-top-force-df01-silver-upgrade-kit' THEN 'Tamiya Top Force DF01 Silver Upgrade Kit'
    WHEN 'tamiya-top-force-df01-black-upgrade-kit' THEN 'Tamiya Top Force DF01 Black Upgrade Kit'
    WHEN 'tamiya-top-force-df01-anodized-j4' THEN 'Tamiya Top Force DF01 Anodized J4'
    WHEN 'tamiya-gearbox-reinforcement-set' THEN 'Tamiya Gearbox Reinforcement Set'
    WHEN 'tamiya-top-force-df01-silver-j4' THEN 'Tamiya Top Force DF01 Silver J4'
    WHEN 'tamiya-top-force-df01-red-upgrade-kit' THEN 'Tamiya Top Force DF01 Red Upgrade Kit'
    WHEN 'tamiya-top-force-df01-black-j7' THEN 'Tamiya Top Force DF01 Black J7'
    WHEN 'tamiya-top-force-df01-black-j3' THEN 'Tamiya Top Force DF01 Black J3'
    WHEN 'tamiya-top-force-df01-blue' THEN 'Tamiya Top Force DF01 Blue'
    WHEN 'tamiya-top-force-df01-silver' THEN 'Tamiya Top Force DF01 Silver'
    WHEN 'tamiya-top-force-df01-black' THEN 'Tamiya Top Force DF01 Black'
    WHEN 'tamiya-top-force-df01-anodized-1' THEN 'Tamiya Top Force DF01 Anodized Set 1'
    WHEN 'tamiya-tt02-red-prop-shaft-bearing-clamp' THEN 'Tamiya TT02 Red Prop Shaft Bearing Clamp'
    WHEN 'tamiya-tt02-blue-prop-shaft-bearing-clamp' THEN 'Tamiya TT02 Blue Prop Shaft Bearing Clamp'
    WHEN 'tamiya-tt02-black-prop-shaft-bearing-clamp' THEN 'Tamiya TT02 Black Prop Shaft Bearing Clamp'
    WHEN 'tamiya-tt02-silver-prop-shaft-bearing-clamp' THEN 'Tamiya TT02 Silver Prop Shaft Bearing Clamp'
    WHEN 'tamiya-trf201-211-201xmw-brass-hinge-pin-brace' THEN 'Tamiya TRF201/211/201XMW Brass Hinge Pin Brace'
    WHEN 'tamiya-dyna-storm-blaster-tr15t-silver-anodized-bulkhead' THEN 'Tamiya Dyna Storm Blaster TR15T Silver Anodized Bulkhead'
    WHEN 'tamiya-top-force-df01-blue-j4' THEN 'Tamiya Top Force DF01 Blue J4'
    WHEN 'tamiya-top-force-df01-black-j4' THEN 'Tamiya Top Force DF01 Black J4'
    WHEN 'tamiya-top-force-df01-red-j4' THEN 'Tamiya Top Force DF01 Red J4'
    WHEN 'tamiya-dyna-storm-blaster-tr15t-blue-d2-d1-hinge-pin-blocks' THEN 'Tamiya Dyna Storm Blaster TR15T Blue D2/D1 Hinge Pin Blocks'
    WHEN 'tamiya-top-force-df01-black-gearbox-cover' THEN 'Tamiya Top Force DF01 Black Gearbox Cover'
    WHEN 'tamiya-super-astute-silver-anodized-bell-cranks' THEN 'Tamiya Super Astute Silver Anodized Bell Cranks'
    WHEN 'tamiya-super-astute-red-anodized-bell-cranks' THEN 'Tamiya Super Astute Red Anodized Bell Cranks'
    WHEN 'tamiya-super-astute-blue-anodized-bell-cranks' THEN 'Tamiya Super Astute Blue Anodized Bell Cranks'
    WHEN 'tamiya-super-astute-black-anodized-bell-cranks' THEN 'Tamiya Super Astute Black Anodized Bell Cranks'
    WHEN 'tamiya-ta02sw-anodized-gearbox-cover' THEN 'Tamiya TA02SW Anodized Gearbox Cover'
    WHEN 'tamiya-dyna-storm-anodized-d7-chassis-brace' THEN 'Tamiya Dyna Storm Anodized D7 Chassis Brace'
    WHEN 'schumacher-procat-xls-bosscat-cougar-silver-bearing-holder' THEN 'Schumacher Pro Cat/XLS/Bosscat/Cougar Silver Bearing Holder'
    WHEN 'schumacher-procat-xls-bosscat-cougar-red-bearing-holder' THEN 'Schumacher Pro Cat/XLS/Bosscat/Cougar Red Bearing Holder'
    WHEN 'schumacher-procat-xls-bosscat-cougar-blue-bearing-holder' THEN 'Schumacher Pro Cat/XLS/Bosscat/Cougar Blue Bearing Holder'
    WHEN 'schumacher-procat-xls-bosscat-cougar-black-bearing-holder' THEN 'Schumacher Pro Cat/XLS/Bosscat/Cougar Black Bearing Holder'
    WHEN 'tamiya-top-force-df01-anodized-servo-posts-2' THEN 'Tamiya Top Force DF01 Anodized Servo Posts Set 2'
    WHEN 'tamiya-dyna-storm-wing-holder-knob' THEN 'Tamiya Dyna Storm Wing Holder Knob'
    WHEN 'tamiya-ta01-ta02-df01-pom-undertray' THEN 'Tamiya TA01/TA02/DF01 POM Undertray'
    WHEN 'tamiya-vqs-carbon-ball-connectors' THEN 'Tamiya VQS Carbon Ball Connectors'
    WHEN 'micro-end-mill-0-3mm' THEN 'Micro End Mill 0.3mm'
    WHEN 'micro-end-mill-0-4mm' THEN 'Micro End Mill 0.4mm'
    WHEN 'tamiya-top-force-df01-silver-steering-brace' THEN 'Tamiya Top Force DF01 Silver Steering Brace'
    WHEN 'tamiya-top-force-df01-red-steering-brace' THEN 'Tamiya Top Force DF01 Red Steering Brace'
    WHEN 'tamiya-top-force-df01-blue-steering-brace-2' THEN 'Tamiya Top Force DF01 Blue Steering Brace Set 2'
    WHEN 'tamiya-top-force-df01-black-steering-brace' THEN 'Tamiya Top Force DF01 Black Steering Brace'
    WHEN 'tamiya-ta02sw-blue-gearbox-cover' THEN 'Tamiya TA02SW Blue Gearbox Cover'
    WHEN 'tamiya-top-force-df01-red-servo-posts' THEN 'Tamiya Top Force DF01 Red Servo Posts'
  END;

-- Make title column required
ALTER TABLE products ALTER COLUMN title SET NOT NULL;